[package]
name = "zome_signals"
version = "0.1.0"
rust-version = "1.75.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust]
non_upper_case_globals = "allow"
unused_doc_comments = "allow"
non_camel_case_types = "allow"
non_snake_case = "allow"
unused_attributes = "allow"

[dependencies]
holochain_serialized_bytes = "=0.0.56"
serde = { version = "=1.0.219", default-features = false }
hdk = { version = "=0.6.0-dev.21", default-features = false }
